### ISSUE TITLE
Invalid Datatype Names

### ISSUE THREAD

**Issue by alanlgirard** [Alexander89/netvar#2]
Looking through the defined datatypes, it looks like there are 2 that are not valid datatypes in CoDeSys.  

|Current|Suggested Change|
|-----|----|
|FLOAT|REAL|
|DOUBLE|LREAL|

CoDeSys Datatypes reference - https://help.codesys.com/webapp/_cds_struct_reference_datatypes;product=codesys;version=3.5.16.0

**Comment by Alexander89** [comment]
Hi, thank you for pointing this out!

Have a look at #3 this should fix it

**Comment by alanlgirard** [comment]
Commit #3 fixes invalid datatype issue.  Thanks!

**Comment by Alexander89** [comment]
@alanlgirard just to satisfy my personal curiosity, may I ask what you use this for?
I love robots and factories. :-)

**Comment by alanlgirard** [comment]
@Alexander89 Currently running Codesys on a raspberry pi with a webserver also on it and stumbled upon your repo that we could leverage to easily pass data back and forth between the two.  The system that we are designing handles production job tracking of plants for the horticulture industry. Thanks for starting this node package!

**Comment by Alexander89** [comment]
Cool case! 
Probably this could be interesting for you:
https://edge-native.github.io/website/
#distributedsystems #edge-native #serverless

Or check out what we do at [actyx](www.Actyx.io)
