### ISSUE TITLE
String Send to PLC Errors

### ISSUE THREAD

**Issue by alanlgirard** [Alexander89/netvar#5]
Tested all of the supported dataypes and everything works well for sending/receiving to a PLC, but I am not able to send a string to the PLC.  I am able to read a string though. Codesys reports an error of Netvar error layout.

**Comment by Alexander89** [comment]
@alanlgirard 
sorry, it just was implemented as "It should work like this". nut never tested.
thanks for being my un-ask :rabbit: 

i publish it with the next tag 
`npm i netvar@next`

I will do proper testing with all types when I'm next to my PLC this evening.
